from os import path
import PySimpleGUI as sg

import json


from path_container import PathContainer

class Gui:

    def __init__(self):
        pass

    def get_data_paths(self, current_path: str) -> PathContainer:
        """
            Paths will be under the 1_Contextual_Interviews folder
            hospitalrisk_path: Path to hospitalrisk_ecart_wpercentilescoring.xlsx
            output_path: Path to autogenerated_study
            hospitalrisk_demo_path: Path to labeled_hospitalrisk_demo.csv
            """
        json_paths = path.join(current_path, "./data_translation_files/paths.json")
        with open(json_paths) as paths_fp:
            paths = json.load(paths_fp)

            path_container = PathContainer()

            layout = [
                [sg.T("")],
                [sg.Text("Choose the output path folder within SEMR - ex. autogenerated_study"),
                sg.Input(default_text=paths["output_path"]),
                sg.FolderBrowse(key="-OutputFolder-")],

                [sg.T("")],
                [sg.Text("Choose the Progress Note Cases Folder - ex. Progress Note Cases"),
                sg.Input(default_text=paths["progress_note_cases_path"]),
                sg.FolderBrowse(key="-ProgressNoteCases-")],

                [sg.T("")],
                [sg.Text("Choose the excel data file - ex. hospitalrisk_ecart_wpercentilescoring.xlsx"),
                sg.Input(default_text=paths["hospitalrisk_path"]),
                sg.FileBrowse(key="-ExcelFile-")],

                [sg.T("")],
                [sg.Text("Choose labeled hospitalrisk_demo - ex. labeled_hospitalrisk_demo.csv"),
                sg.Input(default_text=paths["hospitalrisk_demo_path"]),
                sg.FileBrowse(key="-HospitalriskDemo-")],

                [sg.Button("Submit")]
            ]
            window = sg.Window('Locate File', layout)

            while True:
                event, values = window.read()
                if event == sg.WIN_CLOSED or event == "Exit":
                    break
                elif event == "Submit":
                    # TODO: Need to add checks to determine file validity

                    # Using indexes because the keys don't take into account pre-entered file paths
                    path_container.add_output_path(values[0])
                    path_container.add_progress_note_cases(values[1])
                    path_container.add_hospitalrisk_path(values[2])
                    path_container.add_hospitalrisk_demo(values[3])

                    paths["output_path"] = path_container.get_output_path()
                    paths["progress_note_cases_path"] = path_container.get_progress_note_cases()
                    paths["hospitalrisk_path"] = path_container.get_hospitalrisk_path()
                    paths["hospitalrisk_demo_path"] = path_container.get_hospitalrisk_demo()

                    with open(json_paths, "w") as paths_fp:
                        json.dump(obj=paths, fp=paths_fp, indent=4)

                    window.close()

            return path_container
